### ISSUE TITLE
Most of the entities you remove can be readded via ClientSideOnly TempEntity

### ISSUE THREAD

**Issue by LuxLuma** [YakumoHaruka/l4d2_docs#1]
I'm not sure how much you miss most of these props you remove, i'v using a method of creating a non despawning clientsided prop_physics that does not contribute to server entity count, because it is clientsided.

This would require a plugin to do.

https://github.com/YakumoHaruka/l4d2_docs/tree/master/stripper/maps

**Comment by YakumoHaruka** [comment]
Sorry for the long delay of reply! I have only noticed that there is an issue here just now... 

I have very limited knowledge about this Stripper stuff and mapping... so I'm not quite sure what your point is... Does that mean we could replace the prop_physic entities with some client-side only entities, rather than just blindly removes them? If so, would you mind sharing some experiences on how to achieve that? Like, changing some attributes of the entities, or?

**Comment by LuxLuma** [comment]
Here is a stock for creating clientsided prop physics i would require sourcemod plugin to be made
https://gist.github.com/LuxLuma/f7f97fdd8353172198a258205dca928b

Depends on how much you really miss those props.

**Comment by YakumoHaruka** [comment]
Thank you for showing me the code! These TE_*** SourceMod APIs are new to me, I will take a look at them later when I got time. :)

**Comment by LuxLuma** [comment]
No problem ill go ahead and close this issue.
